apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bm-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CHANGE TO YOURS
    repoURL: 'https://github.com/asmaestro/bm-gitops.git'
    path: overlays/prod
    # CHANGE TO YOURS
    targetRevision: solution-gitops-e2e
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true