apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bm-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CHANGE TO YOURS
    repoURL: 'https://github.com/asmaestro/bm-gitops.git'
    path: overlays/staging
    # CHANGE TO YOURS
    targetRevision: solution-gitops-base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true