apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bm-application-set
  namespace: argocd
spec:
  generators:
  - git:
       # CHANGE TO YOURS
      repoURL: https://github.com/asmaestro/bm-gitops.git
       # CHANGE TO YOURS
      revision: solution-gitops-base
      directories:
      - path: overlays/*
  template:
    metadata:
      name: 'bm-{{path.basename}}'
      labels:
        ApplicationSet: bm.yaml
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        # CHANGE TO YOURS
        repoURL: https://github.com/asmaestro/bm-gitops.git
        # CHANGE TO YOURS
        targetRevision: solution-gitops-base
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true