apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  # workaround related to https://github.com/argoproj/argo-cd/issues/8128
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds/
    targetRevision: kube-prometheus-stack-51.0.3
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
