{{- if and (.Values.prometheus) (.Values.prometheus.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.addonUrl }}
    path: {{ .Values.pathAddons }}/prometheus
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        prometheus:
        {{- toYaml .Values.prometheus | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
